function [x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro,date_time,temp,pressure] = import_tag_data_gyro(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [X_ACCEL,Y_ACCEL,Z_ACCEL,X_GYRO,Y_GYRO,Z_GYRO,DATE_TIME,TEMP,PRESSURE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [X_ACCEL,Y_ACCEL,Z_ACCEL,X_GYRO,Y_GYRO,Z_GYRO,DATE_TIME,TEMP,PRESSURE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [x_accel,y_accel,z_accel,x_gyro,y_gyro,z_gyro,date_time,temp,pressure] = import_tag_data_gyro('gyro_test_data.TXT',1, 269);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/08 09:10:59

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,8,9]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using date
% format string.
try
    dates{7} = datetime(dataArray{7}, 'Format', 'yyyy-MM-dd HH:mm:ss', 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{7} = cellfun(@(x) x(2:end-1), dataArray{7}, 'UniformOutput', false);
        dates{7} = datetime(dataArray{7}, 'Format', 'yyyy-MM-dd HH:mm:ss', 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
    catch
        dates{7} = repmat(datetime([NaN NaN NaN]), size(dataArray{7}));
    end
end

anyBlankDates = cellfun(@isempty, dataArray{7});
anyInvalidDates = isnan(dates{7}.Hour) - anyBlankDates;
dates = dates(:,7);

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,8,9]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
x_accel = cell2mat(rawNumericColumns(:, 1));
y_accel = cell2mat(rawNumericColumns(:, 2));
z_accel = cell2mat(rawNumericColumns(:, 3));
x_gyro = cell2mat(rawNumericColumns(:, 4));
y_gyro = cell2mat(rawNumericColumns(:, 5));
z_gyro = cell2mat(rawNumericColumns(:, 6));
date_time = dates{:, 1};
temp = cell2mat(rawNumericColumns(:, 7));
pressure = cell2mat(rawNumericColumns(:, 8));

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% date_time=datenum(date_time);


